# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5168932bac1c6898ba74dea43533e24df934076f2650bc11ab96353d91a41ec5d90edbb210ec88b904e1040530057f2576c3db94987ff6a6240c4a1178145a8a

test:
  secret_key_base: 111bef83b292bd393cec8f4ab8cd1f8f445cfd05f92de5e8b8965150642c94704f9aea8fb342c563d22180a96465c8d1fe6113860fddbe62171df52b437b93e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
